name: Build SRML Installer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install NuGet
      run: choco install nuget.commandline -y

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet Packages
      run: nuget restore SRML.sln

    - name: Build SRML Installer
      run: msbuild SRMLInstaller\SRMLInstaller.csproj /p:Configuration=Release

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: SRML-Installer
        path: SRMLInstaller\bin\Release\SRMLInstaller.exe
